export const LOGIN_WITH_GOOGLE_REQUEST = "LOGIN_WITH_GOOGLE_REQUEST";
export const LOGIN_WITH_GOOGLE_SUCCESS = "LOGIN_WITH_GOOGLE_SUCCESS";
export const LOGIN_WITH_GOOGLE_FAIL = "LOGIN_WITH_GOOGLE_FAIL";

export const LOGOUT = "LOGOUT";
