export const ADD_EXPENCE_REQUEST = "ADD_EXPENCE_REQUEST";
export const ADD_EXPENCE_SUCCESS = "ADD_EXPENCE_SUCCESS";
export const ADD_EXPENCE_FAIL = "ADD_EXPENCE_FAIL";

export const GET_EXPENCE_REQUEST = "GET_EXPENCE_REQUEST";
export const GET_EXPENCE_SUCCESS = "GET_EXPENCE_SUCCESS";
export const GET_EXPENCE_FAIL = "GET_EXPENCE_FAIL";

export const UPDATE_EXPENCE_REQUEST = "UPDATE_EXPENCE_REQUEST";
export const UPDATE_EXPENCE_SUCCESS = "UPDATE_EXPENCE_SUCCESS";
export const UPDATE_EXPENCE_FAIL = "UPDATE_EXPENCE_FAIL";

export const DELETE_EXPENCE_REQUEST = "DELETE_EXPENCE_REQUEST";
export const DELETE_EXPENCE_SUCCESS = "DELETE_EXPENCE_SUCCESS";
export const DELETE_EXPENCE_FAIL = "DELETE_EXPENCE_FAIL";
