export const ADD_INCOME_REQUEST = "ADD_INCOME_REQUEST";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const ADD_INCOME_FAIL = "ADD_INCOME_FAIL";

export const GET_INCOME_REQUEST = "GET_INCOME_REQUEST";
export const GET_INCOME_SUCCESS = "GET_INCOME_SUCCESS";
export const GET_INCOME_FAIL = "GET_INCOME_FAIL";

export const UPDATE_INCOME_REQUEST = "UPDATE_INCOME_REQUEST";
export const UPDATE_INCOME_SUCCESS = "UPDATE_INCOME_SUCCESS";
export const UPDATE_INCOME_FAIL = "UPDATE_INCOME_FAIL";

export const DELETE_INCOME_REQUEST = "DELETE_INCOME_REQUEST";
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS";
export const DELETE_INCOME_FAIL = "DELETE_INCOME_FAIL";
